### ISSUE TITLE
CICD RegEx Dialogs are failing

### ISSUE THREAD

**Issue by OBULAKSHMIBP** [microsoft/BotFramework-Composer#9627]
Hi Team,

We are configuring CICD for our composer bot solution.

We have Regular Expression dialogs (Which doesn't have lu.dialog) in our bot solution.

While running the CICD pipeline, LUUtil.ps1 file fails as it is looking for a respective "lu.dialog" file.

Please advise us to proceed further on the same. Thanks in advance!!!

**Comment by dmvtech** [comment]
I _believe_ that you just need to remove the bits of yaml that are doing the luis/qna/nlp stuff.

So, you could remove the following from the `buildAndDeploy.yaml`:

```
# Build and deploy LUIS and QnAMaker models
- template: templates/buildAndDeployModels.yaml
  parameters:
    sourceDirectory: "$(System.DefaultWorkingDirectory)/${{ parameters.botProjectDirectory }}"
    yamlDirectory: "$(System.DefaultWorkingDirectory)/${{ parameters.buildYamlDirectory }}"
    botName: "${{ parameters.botName }}"
    luisAuthoringKey: "${{ parameters.luisAuthoringKey }}"
    luisAuthoringRegion: "${{ parameters.luisAuthoringRegion }}"
    qnaSubscriptionKey: "${{ parameters.qnaSubscriptionKey }}"
```

Or if you needed to just remove LUIS, remove the those specific bits from the `buildAndDeployModels.yaml` file. Such as:

```
# Publish LUIS models if luisAuthoringKey is defined
- task: PowerShell@2
  displayName: "Publish LUIS"
  inputs:
    targetType: "filePath"
    filePath: "${{ parameters.yamlDirectory }}/templates/Build-LUIS.ps1"
    arguments: -outputDirectory ./generated -sourceDirectory ./ -crossTrainedLUDirectory ./generated/interruption -authoringKey ${{ parameters.luisAuthoringKey }} -authoringRegion ${{ parameters.luisAuthoringRegion }} -botName ${{ parameters.botName }} 
    # Note: the working directory needs to be set to the bot's source directory
    # to allow for the creation of relative paths in the generated config files.
    workingDirectory: ${{ parameters.sourceDirectory }}
  condition: and(succeeded(), ne(variables['luisAuthoringKey'], ''))
  ```
  
I'm going to close this as it's not a bug or problem with Composer. But feel free to open an issue in the [Documentation](https://learn.microsoft.com/en-us/composer/how-to-cicd) or a Feature Request in the [Samples repo](https://github.com/microsoft/BotBuilder-Samples/issues/new?assignees=&labels=needs-triage%2C+feature-request&projects=&template=-samples-feature-request.md&title=).
